format = """
[░▒▓](#7A8478)\
[  ](bg:#7A8478 fg:#090c0c)\
[](bg:#859289 fg:#7A8478)\
$directory\
[](fg:#859289 bg:#4F5B58)\
$git_branch\
$git_status\
[](fg:#4F5B58 bg:#495156)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#495156 bg:#414B50)\
$time\
[ ](fg:#414B50)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#859289"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4F5B58"
format = '[[ $symbol $branch ](fg:#D3C6AA bg:#4F5B58)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#D3C6AA bg:#4F5B58)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#D3C6AA bg:#4F5B58)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#D3C6AA bg:#4F5B58)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#D3C6AA bg:#4F5B58)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#D3C6AA bg:#4F5B58)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

