- 1.1.14
- _NAME: G502 SE Hero Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, reprogrammable-keys, persistent-remappable-keys,
    divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 0
  _modelId: C08B00000000
  _sensitive: {dpi: true, led_control: true, led_zone_1: true, led_zone_2: false, onboard_profiles: true, report_rate: true}
  _unitId: '93006700'
  dpi: 1050
  led_control: 1
  led_zone_1: !LEDEffectSetting {ID: 1, color: 65535, intensity: 0, period: 108, ramp: 0, speed: 0}
  led_zone_2: !LEDEffectSetting {ID: 1, color: 35723, intensity: 0, period: 100, ramp: 0, speed: 0}
  onboard_profiles: 0
  report_rate: 1
